name: Generate Dependency Updates Changeset

on:
  pull_request_target:
    paths:
      - 'pnpm-lock.yaml'
      - 'package.json'
permissions:
  contents: read

jobs:
  generate-changeset:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 2
          ref: ${{ github.head_ref }}
      - name: Generate Changeset
        run: |
          CHANGESET_NAME="dependency-update-pr${{ github.event.pull_request.number }}.md"
          cat <<EOF > .changeset/$CHANGESET_NAME
          ---
          "ts-graphviz": "patch"
          "@ts-graphviz/core": "patch"
          "@ts-graphviz/common": "patch"
          "@ts-graphviz/ast": "patch"
          "@ts-graphviz/adapter": "patch"
          ---

          ${PR_TITLE}
          EOF
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .changeset/$CHANGESET_NAME
          git commit -m "Add changeset for $CHANGESET_NAME"
          git push
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
